qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name='home-page'),
    path('codedevelopment', views.get_code_development, name='code_development'),
    path('executionhistory', views.get_execution_history, name='execution_history'),
    path('codeinventory',views.code_inventory,name='code_inventory'),
    path('ajax/load-projects/', views.load_projects, name='ajax_load_projects')
]

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reporting_app.urls'))
]

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/models.py
from django.db import models

class Category(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category

class Project(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    project = models.CharField(max_length=50)
    repo = models.CharField(max_length=50, default='')
    branch = models.CharField(max_length=50,default='')
    qac = models.CharField(max_length=50,default='')
    path = models.CharField(max_length=50,default='')
    run_type = models.CharField(max_length=50,default='')

    def __str__(self):
        return self.project



qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('category','project')
        widgets = {'project':forms.Select(attrs={'class':'select'}),
                   }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['project'].queryset=Project.objects.none()






qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/views.py
from . data_api import BitBucket_API as BB
from . data_sql import SQL
from . forms import ProjectForm
from function_library.qacomplete.project import QACProjectAPI


def home(request):
    return render(request, "reporting_app/home.html")

def get_code_development(request):
    return render(request, "reporting_app/code_development.html")

def get_execution_history(request):
    return render(request, "reporting_app/execution_history.html")

from django.http import HttpResponseRedirect
from django.shortcuts import render


from django.views.generic import CreateView
from .models import Category,Project

class ProjectView(CreateView):
    model = Project
    form_class = ProjectForm


from .models import Project
def load_projects(request):
    category_id = request.GET.get('category')
    projects = Project.objects.filter(category_id=category_id).order_by('project')

    return render(request, 'reporting_app/project_dropdown_list_options.html',{'projects':projects})

def code_inventory(request):
    form = ProjectForm

    category_id = request.GET.get('category')
    project_id = request.GET.get('project')

    if project_id is not None:

        category_name = Category.objects.get(id=category_id).category
        project = Project.objects.get(id=project_id)
        project_name = project.project
        repo = project.repo
        branch = project.branch
        qac_project_name = project.qac
        path = project.path
        run_type = project.run_type

        data = BB(repo, branch, path)

        project_id = QACProjectAPI().get_project_id(qac_project_name)

        tests_id = data.get_test(run_type)
        tests = SQL(project_id, tests_id).get_test_title()

        if tests is not None:

            context = {
                'form':form,
                'testlist':tests,
                'category':category_name,
                'project':project_name,
                'repo':repo,
                'branch':branch
            }


            return render(request, 'reporting_app/code_inventory.html', context)
    else:
        return render(request,'reporting_app/code_inventory.html', {'form':form})






qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/base.html
<!DOCTYPE html>
<html>
{% load static %}
{% load activeurl %}

<head>
  <meta charset="UTF-8">
  <title>QA Automation Dashboard</title>
  <style>

  h1 {
    background-color: white;
    color: #43B02A;
    text-align: center
  }

  .header_menu {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #43B02A;
  }

    ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #43B02A;
  }


  li {
    float: left;
  }

  li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }

.active, li:hover {
  background-color: green;
  color: white;
}




  </style>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


</head>

<body>
    <h1 style="color: #43B02A;">QA Automation Dashboard</h1>

<!--    <ul id="menu">-->
<!--        <li class="tab"><a href="home">Home</a></li>-->
<!--        <li class="tab"><a href="codeinventory">Code Inventory</a></li>-->
<!--        <li class="tab"><a href="codedevelopment">Code Development</a></li>-->
<!--        <li class="tab"><a href="executionhistory">Execution History</a></li>-->
<!--    </ul>-->

    {% activeurl %}
        <ul>
            <li> <!-- this <li> will render as <li class="active"> -->
                <a href="/home">
                    Home
                </a>
            </li>
            <li>
                <a href="/codeinventory">
                    Code Inventory
                </a>
            </li>
            <li>
                <a href="/codedevelopment">
                    Code Development
                </a>
            </li>
            <li>
                <a href="/executionhistory">
                    Execution History
                </a>
            </li>
        </ul>
    {% endactiveurl %}




  <div id="project_select" style="margin:10px;">
    {% block project_select %}{% endblock %}
  </div>

  <div id="content" style="margin:10px;">
      <br>
    {% block content %}{% endblock %}
  </div>


{% block js %}

{% endblock js %}


</body>
</html>

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/code_development.html
{% extends 'base.html' %}

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/code_inventory.html
{% extends "reporting_app/project_form.html" %}

{% block search_button %}
<form method="get">
    <button id='search' type="submit">Search</button>
</form>
{% endblock %}

{%  block content %}
{% if project %}
<p>Searched result for the project <b>{{category}}</b>--><b>{{project}}</b> from repo <b>{{repo}}</b> branch <b>{{branch}}:</b></p>


    <table id="table_id" class="display" border='2' align="center">
        <thead>
         <tr>
            <th align="center">ID</th>
            <th align="center">Test ID</th>
            <th align="center">Test Name</th>
            <th align="center">Requirement</th>
            <th align="center">User Story Link</th>
         </tr>

         </thead>
        <tbody>
                {% for test in testlist %}
                    <tr>

                        <TD class="c3" align="center">{{forloop.counter}}</TD>

                        <TD class="c3" align="center">{{test.TestId}}</TD>

                        <TD class="c3" >{{test.Title}}</TD>


                        {% if test.Requirement == None %}
                            <TD class="c3" >Test Is Not Linked To a Requirement</TD>
                        {% else %}
                            <TD class="c3" >{{test.Requirement}}</a></TD>
                        {% endif %}


                        {% if test.Comments == None %}
                            <TD class="c3" >User Story Link Is Not Avaiable</TD>
                        {% else %}
                            <TD class="c3" ><a href="{{test.Comments}}">{{test.Comments}}</a></TD>
                        {% endif %}

                    </tr>
                    {% endfor %}
        </tbody>
            </table>


{% endif %}
{% endblock %}

 {% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
    $(document).ready( function () {
    $('#table_id').DataTable({}
    );
} );
</script>

</div>
{% endblock %}

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/execution_history.html
{% extends 'base.html' %}

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/home.html
{% extends "base.html" %}

{% block content %}
<h3></h3>
{% endblock %}

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/project_dropdown_list_options.html

<option value="">---------</option>
{% for i in projects %}
<option value="{{ i.pk }}">{{ i.project }}</option>
{% endfor %}

qa.automation.web_dashboard/QA_Automation_Generic_Reporting/reporting_project/reporting_app/templates/reporting_app/project_form.html
{% extends 'base.html' %}

{% load static %}

{% block project_select %}

    <form method="get" id="projects" data-projects-url="{% url 'ajax_load_projects' %}" novalidate>
        <p>Please select a project to see all the available automated tests:</p>
        {% csrf_token %}
        {{form}}
        {% block search_button %}{% endblock %}
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_category").change(function () {
          var url = $("#projects").attr("data-projects-url");
          var categoryId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'category': categoryId
            },
            success: function (data) {
              $("#id_project").html(data);
            }
          });
        });

    </script>


{% endblock %}








